server:
  port: 8888
spring:
  redis:
    host: 172.19.0.3
    port: 6379
    database: 0
    password:
    timeout: 30000
    lettuce:
      pool:
        max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8     # 连接池中的最大空闲连接
        min-idle: 0     # 连接池中的最小空闲连接
        max-wait: -1